### ISSUE TITLE
Call store method from another store

### ISSUE THREAD

**Issue by berkayk** [foxhound87/rfx-core#4]
Hi,

Is there any way to call a store's method from another store? For instance, I would like to init app after user has logged in. In user store's login callback, I would like to call app stores init function.

Thanks.

**Comment by foxhound87** [comment]
You can call a store method from everywhere using `dispatch()` ([see the docs](https://github.com/foxhound87/rfx-core/blob/master/DOCUMENTATION.md#actions-dispatcher)) after the stores are initialized. The `init()` method has a special behavior, it will be fired automatically on each store initialization if implemented in the class. You can name it differently and call it with `dispatch('myStoreName.myMethodName', input)`.
