### ISSUE TITLE
Question about dependency upgrades

### ISSUE THREAD

**Issue by mindaugasnakrosis** [foxhound87/rfx-core#9]
Is it possible to upgrade react-router dependency from v3 to v4 (what should be done)?
What about mobx? Version 5 exists which has proxy functionality, but as far as I know rfx-core does not support that high mobx version too.

@foxhound87

**Comment by foxhound87** [comment]
I've updated the package to support mobx v5.
https://github.com/foxhound87/rfx-core/releases/tag/v1.6.1

we already discussed about react-router v4,
it will not be supported due to SSR issues.
https://github.com/foxhound87/rfx-stack/issues/51
https://github.com/foxhound87/rfx-stack/issues/50
